baseURL = "https://ai-circle.pages.dev/"
languageCode = "en-us"
title = "AI Circle"
theme = "ananke"

[params]
  description = "A human-centered discussion on AI, work, culture, and survival"
  show_reading_time = true
  mainSections = ["posts"]